# ArgoCD Blue/Green 배포 예제

apiVersion: argoproj.io/v1alpha1     # apps/v1 대신 argoproj.io/v1alpha1을 사용한다
kind: Rollout  # Deployment 대신 Rollout을 사용한다
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: frontend-vuejs
        image: ghcr.io/ryunchang/vue3:master
        # image: ghcr.io/ryunchang/vue_crud_security:v1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      # containers:
      # - name: rollouts-demo
      #   image: ghc
      #   image: argoproj/rollouts-demo:blue
      #   #image: argoproj/rollouts-demo:green
      #   imagePullPolicy: Always
      #   ports:
      #   - containerPort: 8080
  strategy:
    blueGreen: 
      #activeService는 이전의 배포된 Blue 서비스
      activeService: frontend-service
      
      #previewService는 새롭게 배포될 Green 서비스
      previewService: frontend-service-preview
      
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: false

---
apiVersion: v1	
kind: Service	
metadata:	
  name: frontend-service
  labels:
    app: rollout-bluegreen
spec:	
  ports:	
  - port: 80	
    targetPort: 80
    name: http
  selector:	
    app: rollout-bluegreen
  type: NodePort
# kind: Service
# apiVersion: v1
# metadata:
#   name: frontend-active
# spec:
#   selector:
#     app: rollout-bluegreen
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 8080
#   type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service-preview
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
